### PR TITLE
Add camel-jetty integration test

### PR DESCRIPTION
**Pull request by f2par0**
Upgrade jetty to the 12.0.6 version as in camel 4.4.0. camel-cxf had to be repaired in the process
Add camel-jetty feature and integration test

### CODE REVIEW

**Comment by jbonofre** [comment]
I think we should use TCCL to avoid conflict with pax-web jetty. It means we would have a new port used, but not a problem. I gonna do the review.

**Comment by essobedo** [comment]
This one is outdated

**Comment by f2par0** [comment]
Updated PR to contain only the integration test.

**Comment by essobedo** [comment]
Will move it to the apache repository, so let's close it.

**Pull request closed without merging**
