### PR TITLE
Add camel-slack wrapper

### PR DESCRIPTION
**Pull request by lopushen**
no `http-client` feature was needed on build time

### CODE REVIEW

**Comment by essobedo** [comment]
There is a conflict to resolve

**Comment by essobedo** [comment]
This one no longer builds since the upgrade to Camel 4.5, check how I fixed the cloudevents issue in other wrappers https://github.com/jbonofre/camel-karaf/blob/8ad9a42ec0a6bdf8a384c0387c46db4b5a6162de/components/camel-aws/camel-aws2-ddb/pom.xml#L39-L42

**Comment by lopushen** [comment]
resolved conflicts and added cloudevents optional resolution

**Review by essobedo — APPROVED** [review]
LGTM

**Pull request merged**
